# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "almalinux/9"
  config.vm.box_version = "9.8.20260810"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Common libvirt provider configuration.
  config.vagrant.plugins = "vagrant-libvirt"
  config.vm.provider :libvirt do |libvirt|
    # libvirt.driver = "kvm"
    # libvirt.uri = "qemu:///session"
    libvirt.memory = 1024
    libvirt.cpus = 1
  end
  
  k3s_token = ENV['K3S_TOKEN'] || 'default-dev-token'

  # Server machine (AKA controller)
  config.vm.define "#{ENV['USER']}S" do |control|
    control.vm.hostname = "#{ENV['USER']}S"
    control.vm.network "private_network", ip: "192.168.56.110"
    # k3s needs this port 
    control.vm.network "forwarded_port", guest: 6443, host: 6443, host_ip: "127.0.0.1"
    # Install k3s server mode
    control.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -s - server\
          --write-kubeconfig-mode 644 --token #{k3s_token}
      sudo mkdir -p /home/vagrant/.kube
      sudo cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
      sudo chown -R vagrant:vagrant /home/vagrant/.kube
    SHELL
  end

  # Agent machine (AKA worker)
  config.vm.define "#{ENV['USER']}SW" do |control|
    control.vm.hostname = "#{ENV['USER']}SW"
    control.vm.network "private_network", ip: "192.168.56.111"
    # Install k3s agent mode
    control.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -s - agent \
          --server https://192.168.56.110:6443 --token #{k3s_token}
    SHELL
  end

end
